### ISSUE TITLE
Dockerfile modif request 

### ISSUE THREAD

**Issue by mohanramanujam** [William-Yeh/docker-ansible#21]
Upon installing python related modules you do a cleanup during which you also remove python-pip. It would helpful to not remove this in order to use ansible pip module. Particularly when developing and testing python stacks this is nice to have. It would also be nice to have virtualenv module installed

**Comment by William-Yeh** [comment]
When you work with normal OS machines (physical, virtual, or cloud instances), surely you'll do these steps on your Ansible playbooks (such as installing pip or virtualenv).

Back to the Docker world.

When I first made these Docker images, I had a goal to _mimic original OS base images as close as possible_, so that if my Ansible playbooks lacked any necessary steps (such as installing pip or virtualenv), my Docker images would alert on these defects.

As the number of users grows, the requests for convenient images to work with also grow (e.g., https://github.com/William-Yeh/docker-ansible/issues/14 and https://github.com/William-Yeh/docker-ansible/issues/18  ). I'd like to put a carefully-selected subset of such kinds of requests into the _normal_ variant, which is intended to act as _control machine_.

**Comment by mohanramanujam** [comment]
As with #14, I have to derive from our image to add back functionality like pip which you was needed for install of py libraries and which was eventually removed. I could also do the same i.e. install pip and then remove it once i am done with it or leave it there. If hat is what you are suggesting I will do that.
